### ISSUE TITLE
Syntax coloring not working

### ISSUE THREAD

**Issue by tschertel** [moozzyk/ArduinoCode#1]
How can I enable syntax coloring? It's not working by default.

![vcstudio_arduino](https://cloud.githubusercontent.com/assets/485568/17835121/2735de10-6733-11e6-82ab-8f9fcd206486.png)

![vcstudio_arduino_extensions](https://cloud.githubusercontent.com/assets/485568/17835123/2f8d32ca-6733-11e6-8765-b8e95813d3bd.png)

Arch Linux + VSC 1.4.0

**Comment by moozzyk** [comment]
I was able to repro this on Windows. Will look into it.

**Comment by tschertel** [comment]
Thanks.
If there is anything I can do to help, let me know.

## 

Tomás Schertel

**Comment by TypicalFooBar** [comment]
Same issue for me on Windows 10 - I tried looking into the config files an the tmLanguage files, but I don't know enough about how extensions are setup to understand what's happening.

One thing I did try was replacing the contents of the `./syntaxes/arduino.tmLanguage` file with the default c++ tmLanguage contents - I then added `.ino` files to the list of files and changed the `scopeName` at the bottom to be `source.c++.arduino`. Doing this made syntax highlighting work in `.ino` files using the Arduino language, but it doesn't have all the changes that the original `arduino.tmLanguage` had to support all the arduino functions and syntax. This makes me think it might be an issue with the tmLanguage file itself.

Hope this helps!

**Comment by tschertel** [comment]
Using version 1.5.3, it looks a little better.
Here I show the same sketch. One using C++ and other using Arduino as language mode.

![captura de tela_2016-09-24_19-22-22](https://cloud.githubusercontent.com/assets/485568/18811618/a5daea5c-828c-11e6-9c8b-99b55884afc4.png)

![captura de tela_2016-09-24_19-22-47](https://cloud.githubusercontent.com/assets/485568/18811621/ae56a32e-828c-11e6-9180-67d0f9d97159.png)

C++ laguage mode highlights Arduino key words like pinMode, digitalWrite and digitalRead. But it misses variable types, as byte.
In counterpart, Arduino language mode highlights byte variable as well digitalRead and digitalWrite. But it misses unsigned long and void.
Now, both has pros and cons.

**Comment by moozzyk** [comment]
This is correct - the general issue is that earlier versions of VS Code seemed to have included C++ language definition which was then included by the Arduino language definition. The C++ language definition is apparently no longer included with VS Code by default which breaks Arduino. When I figured this out I concluded that the best way to fix this would be to make the Arduino language definition standalone and maybe even not use the tmLanguage format but native VS Code way of doing this. Sadly, I haven't had a chance to do this yet.

**Comment by TypicalFooBar** [comment]
That makes sense - I'll see if I can make a language file without using include statements for the Arduino language. If I can make it happen, I'll submit a pull request for ya. Either way, good find, you both. :)

**Comment by TypicalFooBar** [comment]
Well, I gave it a go...and failed. I'm gonna back out of trying to figure this one out. But, it seems like you've figured out the issue. Good luck, and thanks for the cool project! 😃

**Comment by moozzyk** [comment]
FWIW - this is the change that broke things: https://github.com/Microsoft/vscode/commit/2cf239dc510027854d31fcab4938d13d191b90ba#diff-d3a31a2edb9f0194e1ed74e3c49f379aR26
I tried to change the included base (C++) syntax but it was not picked up. Anyways, the good news is that it is not required to write everything from scratch.

**Comment by mariusstrom** [comment]
Came to report this as I just started messing with Arduino yesterday and got rapidly irritated by the Arduino built-in code editor. Glad it's been reported and repro'd and hope a solution can be had soon!

**Comment by tschertel** [comment]
So, if we change line 24 of syntaxes/arduino.tmLanguage from <string>source.c++</string> to <string>source.cpp</string> should fix it?

**Comment by TypicalFooBar** [comment]
I tried changing all `c++` to `cpp` in that file as well as the `package.json`, but it didn't seem to work. Maybe I did something wrong, though. @tschertel - maybe you could give it a try and see what happens.

**Comment by moozzyk** [comment]
I think the other blocker is the version specified in the package.json file. I think I have all the required changes here: https://github.com/moozzyk/ArduinoCode/pull/2. Sadly, it's picking the default colors now so it mostly looks like the default C++ colorizer i.e. dull. (You can see that it works when you try `HIGH` in your code. With C++ colorizer it is not getting colorized but with Arduino it is as a  constant).

**Comment by MakerPact** [comment]
Just checking is this still an open issue? Or has it been fixed?

**Comment by moozzyk** [comment]
It's not fixed. Investing in this extension was hard to justify after Microsoft created its own Arduino extension.
